### ISSUE TITLE
config.foodshow.authtoken is needed even with self-hosted ngrokd

### ISSUE THREAD

**Issue by danryu** [express42/vagrant-foodshow#3]
Even though there is apparently no authtoken in the case of self-hosted ngrokd, as that appears to be a ngrok.com feature.

I worked round this by setting a dummy value in Vagrantfile, eg
  config.foodshow.authtoken = "foobar"

**Comment by sample** [comment]
Fixed in 7cc078cd1aed8243fd0ffd435086c421523da6fb. I just released version 1.0.3.
